name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

concurrency:
  group: github-metrics
  cancel-in-progress: true

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
      - name: Detailed Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Vlad1343
          template: classic
          filename: github-metrics.svg
          base: header, activity, community
          config_timezone: Europe/London
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          repositories_affiliations: owner, collaborator, organization_member